### PR TITLE
34 implement addition to database

### LINKED ISSUE #34: Implement addition to database
Currently the build does not support “adding” to the database. We would need to add a function or two to collect input data from the html file and add it to the sqlite database. Refer to CMSC 447 Django tutorial on how to do this. We just need an add an item so that it can be retrieved, it doesn’t need to be fancy.

** Points: 8 **

### PR DESCRIPTION
**Pull request by joshuas4**
Fixes issue of non-functional adds. Adds test cases for addition function

### CODE REVIEW

**Review by Nguyen-Tommy — APPROVED** [review]
Fixed addition functionality and added testing.

**Comment by Electrimatics** [comment]
Please add that the user must run
```bash
python3 manage.py migrate
```
before running the webserver in the "Running the webapp" section in README.md

**Review by Electrimatics — DISMISSED** [review]
See other comment

**Comment by Electrimatics** [comment]
This new feature allows users to input the name of the gate as well as a URL associated with that gate.  The list of gates added to the project will show up in a numbered list with their name and image at the top of the page.

**Pull request merged**
